In [1]:
import numpy as np

In [2]:
X = np.array([
    [1, 2],
    [3, 1],
    [3, 2],
    [1, 4]
])

In [4]:
X.shape

(4, 2)

In [5]:
y = np.array([1, 2, 3, 2])
y.shape

(4,)

In [6]:
# w = (XT.X)-1 @ XT @ Y
w0 = np.ones(X.shape[0])
w0

array([1., 1., 1., 1.])

In [7]:
X = np.column_stack((X, w0))
X

array([[1., 2., 1.],
       [3., 1., 1.],
       [3., 2., 1.],
       [1., 4., 1.]])

In [8]:
w = np.linalg.inv(X.T @ X) @ X.T @ y
w
# parameter terakhir adalah intersep

array([ 0.95,  0.6 , -1.25])

In [ ]:
# prediksi
# y = X @ w + w0

array([[1., 2., 1.],
       [3., 1., 1.],
       [3., 2., 1.],
       [1., 4., 1.]])

In [12]:
ls = [1, 2, 3, 4]
ls[:-1]

[1, 2, 3]

In [19]:
from _base import LinearRegression

In [20]:
linreg = LinearRegression()

In [21]:
linreg.fit(X, y)

In [22]:
linreg.intercept_

2814749767106560.5

In [23]:
linreg.coef_

array([-2.81474977e+15,  5.62949953e+15, -5.62949953e+15])